#!/usr/bin/expect -f
set timeout 40
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "echo '--- DB LOGS ---'; docker logs code-db-1 | tail -n 10; echo '--- BACKEND LOGS ---'; docker logs code-backend-1 | tail -n 20; echo '--- DIRECTUS LOGS ---'; docker logs code-directus-1 | tail -n 20"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
