#!/usr/bin/expect -f
set timeout 30
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "
echo '--- NETSTAT PORTS ---'
netstat -tulpn | grep -E ':(80|443) '
echo '--- DOCKER PS PORTS ---'
docker ps --format '{{.Ports}} {{.Names}}' | grep -E '(80|443)'
"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
