#!/usr/bin/expect -f
set timeout 30
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "docker cp apps/backend/scripts/count_products.py russtanko-russtankoprod-colyja-backend-1:/app/apps/backend/scripts/ && docker exec russtanko-russtankoprod-colyja-backend-1 python /app/apps/backend/scripts/count_products.py"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
