#!/usr/bin/expect -f
set timeout 20
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "echo '--- PATH ---'; echo \$PATH; echo '--- DOCKER BIN ---'; which docker; echo '--- DOCKER VERSION ---'; docker --version; echo '--- COMPOSE VERSION ---'; docker compose version"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
