#!/usr/bin/expect -f
set timeout 60
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"

spawn ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $user@$ip "
cd /etc/dokploy/compose/russtanko-russtankoprod-colyja/code
docker compose -f docker-compose.prod.yml -p russtanko-russtankoprod-colyja up -d --force-recreate db backend directus
"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
