#!/usr/bin/expect -f
set timeout 60
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"
set project_dir "/etc/dokploy/compose/russtanko-russtankoprod-colyja/code"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "cd $project_dir && docker compose -f docker-compose.prod.yml up -d --force-recreate"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
