#!/usr/bin/expect -f
set timeout 120
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab && free -h"

expect {
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
