#!/usr/bin/expect -f
set timeout 30
set ip "194.156.118.128"
set user "root"
set password "MaksimNiretin2602201213!"
set key "~/.ssh/id_rsa"
set cmd [lindex $argv 0]

# Try SSH with key first, then fallback to password if needed
spawn ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -i $key $user@$ip "$cmd"
expect {
  "Enter passphrase" {
    exit 1
  }
  "password:" {
    send "$password\r"
    exp_continue
  }
  eof
}
